# These are supported funding model platforms

github: [skiant] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
liberapay: skiant # Replace with a single Liberapay username
